fix: upgrade react-native-gesture-handler to ~2.30.0 for RN 0.83 compatibility
Previous version ~2.24.0 had C++ compilation errors with RN 0.83 Fabric:
  cpp-adapter.cpp: error: use of undeclared identifier 'shadowNodeFromValue'
Expo SDK 55 bundles ~2.30.0 which is compatible.